// The Red Letters — Complete Passage Data
// Full red-letter passages, not isolated verses

export const THEMES = [
  {
    id:1, icon:"\ud83d\ude4f", title:"Prayer", subtitle:"How Jesus taught us to talk to God.",
    passages:[
      {
        id:"1_1", title:"On Prayer, Hypocrisy, and the Lord's Prayer",
        text:"And when you pray, you must not be like the hypocrites. For they love to stand and pray in the synagogues and at the street corners, that they may be seen by others. Truly, I say to you, they have received their reward. But when you pray, go into your room and shut the door and pray to your Father who is in secret. And your Father who sees in secret will reward you.\n\nAnd when you pray, do not heap up empty phrases as the Gentiles do, for they think that they will be heard for their many words. Do not be like them, for your Father knows what you need before you ask him.\n\nPray then like this:\n\nOur Father in heaven, hallowed be your name. Your kingdom come, your will be done, on earth as it is in heaven. Give us this day our daily bread, and forgive us our debts, as we also have forgiven our debtors. And lead us not into temptation, but deliver us from evil.\n\nFor if you forgive others their trespasses, your heavenly Father will also forgive you, but if you do not forgive others their trespasses, neither will your Father forgive your trespasses.",
        ref:"Matthew 6:5-15", translation:"ESV", gospel:"matthew",
        context:"Jesus is in the middle of the Sermon on the Mount, delivering the most concentrated ethical and spiritual teaching ever recorded. He has already addressed anger, lust, oaths, and retaliation. Now He turns to prayer \u2014 not as a new topic, but as the heartbeat of the life He has been describing.\n\nHe addresses a specific problem visible in the religious culture around Him: prayer as performance. The Pharisees were known for their elaborate public prayers, designed as much to cultivate a reputation for holiness as to communicate with God. Jesus does not say \"if you pray\" \u2014 He says \"when you pray,\" assuming His disciples will. What He addresses is the corruption of the practice.",
        meaning:"The passage contains three distinct movements. First, Jesus exposes the problem: prayer that is oriented toward a human audience has already received its full reward \u2014 social approval. It has no further spiritual power because it was never addressed to God.\n\nSecond, He warns against a different corruption: the Gentile assumption that God is moved by the sheer volume of words. The antidote is not fewer words but a different understanding of God \u2014 a Father who already knows what His children need before they ask.\n\nThird, Jesus gives the Lord's Prayer \u2014 not as a formula to recite but as a model of what genuine prayer looks like. It begins with God (hallowed be your name), moves to God's agenda (your kingdom, your will), and only then addresses human need (bread, forgiveness, protection). The sequence is the instruction: God-orientation precedes self-petition.\n\nThe closing condition is striking: Jesus ties the Father's forgiveness directly to whether the disciple extends forgiveness to others. This is not a transactional formula but a description of spiritual reality \u2014 a heart that has genuinely received forgiveness will be a heart that extends it.",
        lexicon:[{word:"Father",original:"Ἀββᾶ (Abba)",language:"Aramaic",meaning:"Father — the intimate, family-room word for father, not the formal address.",note:"Jesus prayed in Aramaic. Abba was the everyday word a child used at home — closer to \"Papa\" than to \"Father, sir.\" Paul preserved the Aramaic word in his Greek letters (Rom 8:15) because no Greek equivalent carried the same family intimacy."},{word:"hallowed",original:"ἁγιάζω (hagiazō)",language:"Greek",meaning:"To set apart as holy; to treat as utterly sacred.",note:"\"Hallowed be Your name\" is a request, not a description — \"may Your name be set apart as holy.\" The first petition of the Lord's Prayer asks for God's name to be honored as sacred, in this praying person first, then in the world."}],
        apply:"Take the Lord's Prayer as a structure, not a script. Pray through it phrase by phrase, expanding each into your own words and your specific situation today. What does \"hallowed be your name\" look like in your workplace, your household, your most difficult relationship? Where is God's kingdom not yet come in your immediate world? What bread \u2014 provision, clarity, courage \u2014 do you need today? Who do you need to forgive in order to stand before God with open hands?",
        prayer:"Our Father in heaven, I begin with You \u2014 not with my needs, but with Your name. Be honored in my life today. Your kingdom come into the places where I have been king. Your will be done in the decisions I have been making alone. Give me what I actually need today \u2014 I trust Your assessment over mine. Forgive me the ways I have failed this week, and I release now the people who have failed me. Lead me away from the places that would undo me. You see me in secret. You know what I need before I ask. I come to You honestly. Amen.",
      },
      {
        id:"1_2", title:"Ask, Seek, Knock",
        text:"Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you. For everyone who asks receives, and the one who seeks finds, and to the one who knocks it will be opened.\n\nOr which one of you, if his son asks him for bread, will give him a stone? Or if he asks for a fish, will give him a serpent? If you then, who are evil, know how to give good gifts to your children, how much more will your Father who is in heaven give good things to those who ask him!",
        ref:"Matthew 7:7-11", translation:"ESV", gospel:"matthew",
        context:"This passage closes the Sermon on the Mount's section on prayer, following directly after the Lord's Prayer. The Greek verbs are in the continuous present tense \u2014 \"keep asking, keep seeking, keep knocking\" \u2014 indicating that Jesus is not describing a one-time event but a sustained orientation of life toward God in prayer.",
        meaning:"The argument moves from human experience to divine character. If even fallen, flawed human fathers give their children bread when they ask \u2014 not stones, not serpents \u2014 how much more will the perfect Father respond to His children who come to Him?\n\nThe guarantee Jesus makes is categorical: everyone who asks receives. This is not a promise that every specific request will be answered as imagined, but that the posture of asking is never met with silence, absence, or cruelty. The Father's character is the foundation of persistent prayer.",
        lexicon:[{word:"ask",original:"αἰτέω (aiteō)",language:"Greek",meaning:"To ask, to request something from someone with the right to give it.",note:"Jesus uses aiteō in present-tense imperative — \"keep on asking.\" The Greek tense matters: not a single request, but ongoing posture. Aiteō is the prayer of a child to a parent — appropriate dependence, not begging."},{word:"seek",original:"ζητέω (zēteō)",language:"Greek",meaning:"To seek, to search, to pursue what is hidden until found.",note:"Zēteō is more than asking — it is searching. Asking might be passive; seeking requires action. Jesus pairs them deliberately: ask (verbal) + seek (pursue) + knock (act). The threefold pattern resists passive prayer."}],
        apply:"What have you stopped asking for because the answer seemed delayed or unclear? The invitation is to return to the asking \u2014 not to badger God, but to stay in the conversation, trusting that the Father who gives bread, not stones, is responding in ways you may not yet see. Identify one specific request you have set aside and bring it back today.",
        prayer:"Father, I confess I have stopped knocking at some doors. I have interpreted silence as rejection and absence as abandonment. You give bread, not stones. You are not cruel. I bring back the request I set aside. I keep asking. I keep seeking. I keep knocking. Not because I can wear You down, but because the conversation itself is a gift and You are faithful. Amen.",
      },
      {
        id:"1_3", title:"The Persistent Widow",
        text:"In a certain city there was a judge who neither feared God nor respected man. And there was a widow in that city who kept coming to him and saying, \"Give me justice against my adversary.\" For a while he refused, but afterward he said to himself, \"Though I neither fear God nor respect man, yet because this widow keeps bothering me, I will give her justice, so that she will not beat me down by her continual coming.\"\n\nHear what the unrighteous judge says. And will not God give justice to his elect, who cry to him day and night? Will he delay long over them? I tell you, he will give justice to them speedily. Nevertheless, when the Son of Man comes, will he find faith on earth?",
        ref:"Luke 18:1-8", translation:"ESV", gospel:"luke",
        context:"Luke introduces this parable with Jesus's explicit statement of its purpose: \"He told them a parable to the effect that they ought always to pray and not lose heart.\" This is the only parable in the Gospels where Jesus tells us the meaning before He tells the story \u2014 a signal that the danger He is addressing, giving up in prayer, is urgent.",
        meaning:"The parable works by contrast, not comparison. The judge is explicitly unjust \u2014 he neither fears God nor respects people. He grants the widow's request not out of justice but self-interest. Jesus then makes the argument from lesser to greater: if even an unjust judge can be moved by persistent appeal, how much more will a just and loving Father respond to His children who cry to Him day and night?\n\nThe final question \u2014 \"will he find faith on earth when the Son of Man comes?\" \u2014 identifies persistent prayer with faith. To stop praying is to stop believing. To keep praying is the practice of trust in the midst of apparent silence.",
        lexicon:[{word:"vindication",original:"ἐκδίκησις (ekdikēsis)",language:"Greek",meaning:"Vindication; justice rendered; the righting of a wrong.",note:"The widow keeps asking for ekdikēsis — for the wrong done to her to be set right. Jesus uses her persistence as a model for prayer that does not give up. The God being prayed to is not the indifferent judge — He is the loving Father who promises ekdikēsis speedily."},{word:"lose heart",original:"ἐγκακέω (enkakeō)",language:"Greek",meaning:"To grow weary, to lose heart, to give up under prolonged effort.",note:"Luke 18:1 names the parable's purpose: to teach \"always to pray and not enkakeō.\" The temptation in delayed prayer is exactly this — the slow erosion of heart that translates into the slow stopping of prayer. Jesus warns against it."}],
        apply:"What have you given up praying for because you grew discouraged? The widow did not stop because the judge didn't respond immediately. She kept coming. Name specifically what you have quietly abandoned in prayer and bring it back \u2014 not because you can exhaust God, but because continuing to ask is itself an act of faith that He is just and He is listening.",
        prayer:"Father, I have lost heart. I have stopped coming because I interpreted the delay as a no. But You are not the unjust judge \u2014 You are the Father who is just and good and attentive. I come back to the door. I bring back what I had set aside. I will not stop coming. Give justice to what I carry. I trust Your timing even when I do not understand it. Amen.",
      },
      {
        id:"1_4", title:"The Pharisee and the Tax Collector",
        text:"Two men went up into the temple to pray, one a Pharisee and the other a tax collector. The Pharisee, standing by himself, prayed thus: \"God, I thank you that I am not like other men, extortioners, unjust, adulterers, or even like this tax collector. I fast twice a week; I give tithes of all that I get.\"\n\nBut the tax collector, standing far off, would not even lift up his eyes to heaven, but beat his breast, saying, \"God, be merciful to me, a sinner!\"\n\nI tell you, this man went down to his house justified, rather than the other. For everyone who exalts himself will be humbled, but the one who humbles himself will be exalted.",
        ref:"Luke 18:9-14", translation:"ESV", gospel:"luke",
        context:"Luke tells us Jesus addressed this parable specifically \"to some who trusted in themselves that they were righteous, and treated others with contempt.\" It follows immediately after the parable of the persistent widow \u2014 both are about prayer, but from opposite angles: persistence (widow) and posture (tax collector).",
        meaning:"The Pharisee's prayer is technically impressive and factually accurate \u2014 he does fast twice a week and tithe everything. But his prayer is addressed to himself (the Greek says he \"prayed with himself\") and functions as a r\u00e9sum\u00e9 presented to God rather than a genuine encounter with Him.\n\nThe tax collector comes with nothing to offer but his need. His posture \u2014 standing far off, eyes down, beating his chest \u2014 communicates the condition of his interior: he is not managing his relationship with God, he is desperate for it. And this man went home justified. Not the Pharisee.\n\nJesus reverses the religious expectation entirely: the spiritual achiever is not accepted, the acknowledged sinner is. The criterion is not performance but posture \u2014 humble dependence rather than self-sufficient presentation.",
        lexicon:[{word:"be merciful",original:"ἱλάσκομαι (hilaskomai)",language:"Greek",meaning:"To be propitious, to extend mercy toward, to satisfy what was owed.",note:"The tax collector prays \"God, hilaskomai me a sinner\" — literally, \"be propitiated toward me.\" The verb implies that something needs to be settled, and the petitioner cannot settle it himself. He throws himself on God's willingness to accept a substitute payment."},{word:"justified",original:"δικαιόω (dikaioō)",language:"Greek",meaning:"To declare righteous; to render a verdict of acquittal.",note:"Jesus says the tax collector \"went down to his house dikaioō-ed\" — declared righteous — rather than the Pharisee. The verdict is legal, not therapeutic. The man who saw himself as a sinner before God left counted as righteous; the man who saw himself as righteous left without that verdict."}],
        apply:"Before your next prayer, ask yourself: am I presenting a r\u00e9sum\u00e9 or arriving in need? The Pharisee's prayer fails not because his actions were wrong but because his self-sufficiency left no room for grace. Come to God the way the tax collector came \u2014 with a specific acknowledgment of your actual condition, not a summary of your spiritual accomplishments.",
        prayer:"God, be merciful to me, a sinner. That is the prayer. I come with nothing to prove. I stand far off in my own awareness of what I am. I do not lift my eyes in confidence of my own goodness. I beat my chest. Be merciful to me. I do not come with a list of what I have done. I come with what I am. Justify me the way You justified him. Amen.",
      },
    ]
  },
  {
    id:2, icon:"\u2764\ufe0f", title:"Love", subtitle:"The command that contains all others.",
    passages:[
      {
        id:"2_1", title:"The Greatest Commandment",
        text:"You shall love the Lord your God with all your heart and with all your soul and with all your mind. This is the great and first commandment. And a second is like it: You shall love your neighbor as yourself. On these two commandments depend all the Law and the Prophets.",
        ref:"Matthew 22:37-40", translation:"ESV", gospel:"matthew",
        context:"A Pharisee \u2014 described as a lawyer \u2014 came to test Jesus with a legal question: \"Which is the great commandment in the Law?\" This was not an innocent inquiry; it was a trap designed to get Jesus to prioritize some commands over others and open Him to critique. Jesus answered not by choosing a side in a legal debate but by synthesizing all 613 commandments into two.",
        meaning:"The first commandment (Deuteronomy 6:5) is total: heart, soul, and mind \u2014 every faculty, every dimension of the self oriented toward God. There is no compartment exempt from this love.\n\nThe second commandment (Leviticus 19:18) is \"like it\" \u2014 not secondary in importance but parallel in structure. The love of neighbor flows from the love of God and cannot be separated from it. The person who genuinely loves God will love the person made in God's image.\n\n\"On these two commandments depend all the Law and the Prophets\" \u2014 Jesus is not replacing the law. He is revealing what the law always was: a description of what love looks like in practice, organized by direction (toward God, toward people).",
        lexicon:[{word:"love",original:"ἀγαπάω (agapaō)",language:"Greek",meaning:"To love with committed, willed love; the love of decision more than feeling.",note:"The verb form of agapē. When Jesus quotes the Shema (Deut 6:5) — love the LORD with all your heart, soul, mind, strength — He uses agapaō. The kind of love commanded is the kind that involves the will, not just the feelings. Decision precedes emotion."},{word:"whole",original:"ὅλος (holos)",language:"Greek",meaning:"Whole, entire, complete; without any part held back.",note:"Jesus repeats holos four times — whole heart, whole soul, whole mind, whole strength. The commandment refuses partial allegiance. Love that holds back any part is not yet the love commanded. The English word \"holocaust\" (\"wholly burned\") derives from this root — total, unreserved."}],
        apply:"Where have you separated these two commandments \u2014 treating devotion to God as a substitute for love of people, or treating love of people as a substitute for devotion to God? They cannot be separated. Identify the most difficult person in your life right now. That person is the specific location where the second commandment becomes real today. What does one concrete act of love toward them look like?",
        prayer:"Lord, I want to love You with all my heart and all my soul and all my mind. But I know my love is partial. I give You the easy parts and manage the rest myself. Take all of me. And teach me to love the people around me with the same seriousness \u2014 not when they earn it, not when I feel it, but as a commitment that flows from loving You. They bear Your image. Let me treat them accordingly. Amen.",
      },
      {
        id:"2_2", title:"The New Commandment",
        text:"Now is the Son of Man glorified, and God is glorified in him. If God is glorified in him, God will also glorify him in himself, and glorify him at once.\n\nLittle children, yet a little while I am with you. You will seek me, and just as I said to the Jews, so now I also say to you, \"Where I am going you cannot come.\"\n\nA new commandment I give to you, that you love one another: just as I have loved you, you also are to love one another. By this all people will know that you are my disciples, if you have love for one another.",
        ref:"John 13:31-35", translation:"ESV", gospel:"john",
        context:"This is the upper room, the night before the crucifixion. Judas has just left to betray Jesus. In this moment \u2014 knowing full well what is coming \u2014 Jesus speaks tenderly to the remaining disciples. He calls them \"little children\" (the only time in the Gospels He uses this term). He is about to leave them, and He wants them to know what matters most.",
        meaning:"The word \"new\" (kainos) signals something qualitatively different from the existing commandment to love your neighbor as yourself. What is new is the standard: not \"as yourself\" but \"as I have loved you.\" Jesus points to His own love \u2014 a love that is about to be demonstrated in the most extreme act of self-giving imaginable \u2014 as the measure.\n\nThe sign of discipleship is not theological precision, spiritual gifts, or moral achievement. It is love of one another. The watching world will identify followers of Jesus not by what they believe but by how they treat each other. The community of disciples is meant to be a visible demonstration of a different kind of love \u2014 one that the surrounding culture has no natural explanation for.",
        lexicon:[{word:"new",original:"καινός (kainos)",language:"Greek",meaning:"New in kind, qualitatively new; not just recent but unprecedented.",note:"Jesus calls His commandment kainos. The same word from AS1 W1 (new creation). Why kainos? The command to love is not new in time — Leviticus 19:18 commanded it. What is kainos is the standard: \"as I have loved you.\" Cross-shaped love is the unprecedented part."},{word:"one another",original:"ἀλλήλους (allēlous)",language:"Greek",meaning:"One another; reciprocally; mutually among the same group.",note:"Allēlous appears about 100 times in the New Testament. Christianity is structurally allēlous — believers cannot follow Jesus alone. The new commandment cannot be obeyed in solo. It requires others to love, and others to love you."}],
        apply:"Jesus said \"as I have loved you\" \u2014 which means the standard includes loving the person who will betray you (Judas had just left), the person who will deny you (Peter), and the people who will abandon you (the rest). Who in your community do you love only when they perform well? The standard is \"as I have loved you\" \u2014 not conditionally, not when earned, but freely and persistently.",
        prayer:"Jesus, You loved me while I was still Your enemy. You washed the feet of the one who would betray You. That is the standard You have set. I cannot produce that kind of love on my own. Give it to me. Let it flow through me to the people I find difficult, the people who have let me down, the people I am tempted to write off. Let the community around me see something they cannot explain except by You. Amen.",
      },
      {
        id:"2_3", title:"Love Your Enemies",
        text:"You have heard that it was said, \"You shall love your neighbor and hate your enemy.\" But I say to you, Love your enemies and pray for those who persecute you, so that you may be sons of your Father who is in heaven. For he makes his sun rise on the evil and on the good, and sends rain on the just and on the unjust.\n\nFor if you love those who love you, what reward do you have? Do not even the tax collectors do the same? And if you greet only your brothers, what more are you doing than others? Do not even the Gentiles do the same?\n\nYou therefore must be perfect, as your heavenly Father is perfect.",
        ref:"Matthew 5:43-48", translation:"ESV", gospel:"matthew",
        context:"This is the final and most radical of the six \"you have heard... but I say to you\" contrasts in the Sermon on the Mount. Jesus has been systematically radicalizing the Torah \u2014 not abolishing it but extending its demands from external behavior to internal intention. This final contrast takes aim at the most fundamental boundary of human ethics: who deserves love.",
        meaning:"The command to \"hate your enemy\" was never in the Torah \u2014 it was a cultural inference, a permission people had granted themselves. Jesus dismantles it entirely. The love He requires is not sentimental affection but committed, active goodwill \u2014 demonstrated first in prayer, which is the spiritual discipline that most directly reshapes the heart toward another person.\n\nThe standard He gives \u2014 \"as your heavenly Father is perfect\" \u2014 is not meant to produce despair but to define the direction. God sends rain on the just and the unjust alike. His love is not conditional on the response of its recipients. The disciples of Jesus are called to embody this same non-conditional love, which is only possible when it flows from genuine connection to a God who loves this way.",
        lexicon:[{word:"enemy",original:"ἐχθρός (echthros)",language:"Greek",meaning:"An enemy; one actively hostile, not just unfriendly.",note:"Echthros is not \"someone you dislike.\" It is someone who actively opposes you. Jesus does not command loving people we find awkward — He commands loving those who would harm us. The difficulty is the point. Easy love is no proof of being God's child."},{word:"perfect",original:"τέλειος (teleios)",language:"Greek",meaning:"Complete, mature; reached the intended end.",note:"\"Be teleios as your heavenly Father is teleios.\" Teleios does not mean flawless in modern English sense. It means complete, mature, having reached the design. The Father is teleios in His love because His love extends even to enemies. Christian maturity is measured by the same standard."}],
        apply:"Name your enemy \u2014 not a category, but a specific person who has wronged you, dismissed you, or actively worked against you. Now pray for them. Not about them \u2014 for them. Ask God specifically to bless them, to meet their genuine needs, to do them good. You do not have to feel it to do it. The feeling may follow the action. The prayer is the discipline that begins to reshape the heart.",
        prayer:"Father, I name the person who is my enemy right now. I do not feel love for them. But You make Your sun rise on them the same as on me. You send rain on them the same as on me. I choose to pray for them: bless them, meet them, do them genuine good. I release my right to withhold goodwill from them. Do in my heart what I cannot do on my own. Amen.",
      },
      {
        id:"2_4", title:"Remain in My Love",
        text:"As the Father has loved me, so have I loved you. Abide in my love. If you keep my commandments, you will abide in my love, just as I have kept my Father's commandments and abide in his love. These things I have spoken to you, that my joy may be in you, and that your joy may be full.\n\nThis is my commandment, that you love one another as I have loved you. Greater love has no one than this, that someone lay down his life for his friends. You are my friends if you do what I command you. No longer do I call you servants, for the servant does not know what his master is doing; but I have called you friends, for all that I have heard from my Father I have made known to you.\n\nYou did not choose me, but I chose you and appointed you that you should go and bear fruit and that your fruit should abide, so that whatever you ask the Father in my name, he may give it to you. These things I command you, so that you will love one another.",
        ref:"John 15:9-17", translation:"ESV", gospel:"john",
        context:"This passage is from the upper room discourse on the night before the crucifixion. Jesus has just finished the vine-and-branches teaching. Now He presses deeper into what abiding looks like \u2014 it is a love relationship modeled on the love between the Father and the Son, and its outward expression is love for one another.",
        meaning:"The architecture of love Jesus describes moves from the source outward: the Father loves the Son; the Son loves the disciples with that same love; the disciples love one another with that same love. Each level is a conduit of the same love, not a diluted version of it.\n\nThe definition Jesus gives of the greatest love \u2014 laying down one's life for one's friends \u2014 is not abstract. He is hours from demonstrating it. And He has redefined the relationship: no longer servants but friends. Friends are trusted with the master's full counsel. Friends are chosen, not employees. The disciples have been elected into this friendship.\n\nThe purpose of this love is fruit that abides \u2014 lasting transformation in people's lives that outlasts any single moment or season.",
        lexicon:[{word:"abide",original:"μένω (menō)",language:"Greek",meaning:"To remain, to stay, to continue in a place or relationship.",note:"The same word from AS1 W50. Jesus says \"abide in My love\" — meaning love is a place to live in, not just a feeling to experience. The verb is in the imperative: stay there. The Christian's task is to remain where Christ has placed them — in His love."},{word:"friends",original:"φίλος (philos)",language:"Greek",meaning:"Friend; one bound by chosen affection rather than mere obligation.",note:"\"I have called you friends\" (philous). The shift from servant to philos is monumental. A doulos (slave) does what is commanded; a philos knows the master's mind. Jesus closes the distance, makes His followers insiders. Friendship with God is the relationship He extends."}],
        apply:"Jesus says \"you did not choose me, but I chose you.\" This is the foundation of the love He commands \u2014 it flows from His prior choice of you, not from your worthiness or consistency. Where are you trying to generate love for others from your own emotional reserves rather than from the knowledge that you are first loved and chosen? Rest in the election before you attempt the command.",
        prayer:"Jesus, You loved me as the Father has loved You. That is an infinite love applied to a finite person. I cannot exhaust it. I rest in the fact that You chose me \u2014 before I performed well, before I was consistent, before I understood what I was entering. From that resting place, let love flow from me to the people around me. I cannot manufacture it. But You can produce it through a branch that stays connected. Amen.",
      },
    ]
  },
  {
    id:3, icon:"\ud83d\udc51", title:"The Kingdom", subtitle:"Already here. Not yet complete.",
    passages:[
      {
        id:"3_1", title:"The Beatitudes and the Kingdom",
        text:"Blessed are the poor in spirit, for theirs is the kingdom of heaven.\nBlessed are those who mourn, for they shall be comforted.\nBlessed are the meek, for they shall inherit the earth.\nBlessed are those who hunger and thirst for righteousness, for they shall be satisfied.\nBlessed are the merciful, for they shall receive mercy.\nBlessed are the pure in heart, for they shall see God.\nBlessed are the peacemakers, for they shall be called sons of God.\nBlessed are those who are persecuted for righteousness' sake, for theirs is the kingdom of heaven.\n\nBlessed are you when others revile you and persecute you and utter all kinds of evil against you falsely on my account. Rejoice and be glad, for your reward is great in heaven, for so they persecuted the prophets who were before you.",
        ref:"Matthew 5:3-12", translation:"ESV", gospel:"matthew",
        context:"Jesus has gone up on a mountain and sat down \u2014 the posture of a rabbi teaching with authority. Crowds have followed. He opens His mouth and delivers the Beatitudes \u2014 the opening of what would become the most famous extended teaching in history. He begins not with commands but with declarations about who is blessed.",
        meaning:"The Beatitudes invert every human assumption about who is blessed. The world blesses the confident, the satisfied, the assertive, the uncompromising, and the comfortable. Jesus blesses the poor in spirit, the mourning, the meek, the hungry, the persecuted.\n\nEach beatitude is a declaration about a present or future reality, not a strategy for self-improvement. They describe the people to whom the kingdom already belongs or is moving toward. The progression is not a ladder to climb but a portrait of the person shaped by kingdom values.\n\nThe poor in spirit and the persecuted form a bracket \u2014 both receive \"the kingdom of heaven\" in the present tense (\"theirs is\"), while the middle beatitudes receive future promises. The kingdom belongs now to those who are most aware of their need for it.",
        lexicon:[{word:"blessed",original:"μακάριος (makarios)",language:"Greek",meaning:"Blessed; deeply, divinely happy; flourishing under God's favor.",note:"Makarios is not the same as \"happy\" in English. It is the settled, deep flourishing that belongs to someone aligned with God's reality. The Beatitudes pronounce makarios over surprising people — the poor in spirit, the mourning, the meek. Worldly flourishing categories are inverted."},{word:"poor in spirit",original:"πτωχός τῷ πνεύματι (ptōchos tō pneumati)",language:"Greek",meaning:"Beggar-poor in spirit; spiritually bankrupt, knowing it.",note:"Ptōchos is the strongest Greek word for poor — describing a beggar with nothing. To be ptōchos in spirit is to know you bring nothing of value to God on your own. This is the entry point into the kingdom: arrival with empty hands. The proud cannot enter; the bankrupt can."}],
        apply:"Which of the Beatitudes describes your current condition most accurately? Not which one you aspire to, but which one fits where you actually are right now? Mourn? Meek? Hungry for righteousness? The Beatitudes are not aspirational goals \u2014 they are promises directed at specific conditions. Receive the promise that corresponds to where you actually are today.",
        prayer:"Lord, I am probably more of these than I realize. I am poor in spirit in areas I have not admitted. I am mourning things I have not named. I am hungry for what only You can give. I receive now the promises that belong to my actual condition \u2014 the kingdom, the comfort, the inheritance, the satisfaction. I do not have to pretend to be somewhere I am not. You meet me exactly here. Amen.",
      },
      {
        id:"3_2", title:"The Parables of the Kingdom",
        text:"The kingdom of heaven is like a grain of mustard seed that a man took and sowed in his field. It is the smallest of all seeds, but when it has grown it is larger than all the garden plants and becomes a tree, so that the birds of the air come and make nests in its branches.\n\nThe kingdom of heaven is like leaven that a woman took and hid in three measures of flour, till it was all leavened.\n\nThe kingdom of heaven is like treasure hidden in a field, which a man found and covered up. Then in his joy he goes and sells all that he has and buys that field.\n\nAgain, the kingdom of heaven is like a merchant in search of fine pearls, who, on finding one pearl of great value, went and sold all that he had and bought it.",
        ref:"Matthew 13:31-33, 44-46", translation:"ESV", gospel:"matthew",
        context:"Jesus has been teaching the crowds from a boat on the Sea of Galilee in a long sequence of kingdom parables. These four compressed parables give different aspects of what the kingdom is like \u2014 its growth, its pervasiveness, its hiddenness, and its supreme value.",
        meaning:"The mustard seed and the leaven describe the kingdom's hidden, organic, unstoppable growth. It begins as the smallest thing \u2014 a carpenter's son, a handful of disciples \u2014 and expands in ways that defy the original scale. The leaven works invisibly but pervasively through everything it touches.\n\nThe hidden treasure and the pearl each describe the response of a person who has truly seen the kingdom. In both cases, the response is immediate, total, and joyful. The man who found the treasure does not grieve what he sold \u2014 he sells \"in his joy.\" The merchant does not reluctantly trade down \u2014 he recognizes what he has found and acts accordingly.\n\nTogether these parables say: the kingdom starts small and invisible, grows unstoppably, and when you truly see it, you will recognize it as worth more than everything else you possess.",
        lexicon:[{word:"parable",original:"παραβολή (parabolē)",language:"Greek",meaning:"A parable; a placing alongside, a comparison made to illuminate.",note:"From para (alongside) + ballō (to throw). A parabolē places a story alongside a deeper reality so the second can be seen through the first. Jesus's parables are not simple morality tales — they are kingdom truths placed alongside everyday situations so listeners can recognize what would otherwise be invisible."},{word:"kingdom",original:"βασιλεία (basileia)",language:"Greek",meaning:"Kingdom; the realm and reign of a king.",note:"Basileia is more about reign than territory. The Greek emphasizes the king's active rule, not the borders of his land. The kingdom of God is where God's reign is recognized and obeyed — currently invisible to those outside, increasingly real to those inside."}],
        apply:"Have you found the kingdom the way these men found the treasure and the pearl \u2014 with such clarity of recognition that giving everything for it felt like joy, not sacrifice? Or are you still treating the kingdom as one investment in a portfolio? The merchant was an expert \u2014 he had seen many pearls. His recognition was informed. What would it take for you to see the kingdom with that level of clarity?",
        prayer:"Lord, let me see Your kingdom the way the merchant saw the pearl. Not vaguely. Not theoretically. With the recognition that makes everything else look like a fair trade. Give me that clarity. Give me that joy. I want to sell everything for what You are building \u2014 not reluctantly, not as a sacrifice, but because I have truly seen what it is. Open my eyes to the kingdom. Amen.",
      },
      {
        id:"3_3", title:"The Prodigal Son",
        text:"A man had two sons. And the younger of them said to his father, \"Father, give me the share of property that is coming to me.\" And he divided his property between them. Not many days later, the younger son gathered all he had and took a journey into a far country, and there he squandered his property in reckless living. And when he had spent everything, a severe famine arose in that country, and he began to be in need. So he went and hired himself out to one of the citizens of that country, who sent him into his fields to feed pigs. And he was longing to be fed with the pods that the pigs ate, and no one gave him anything.\n\nBut when he came to himself, he said, \"How many of my father's hired servants have more than enough bread, but I perish here with hunger! I will arise and go to my father, and I will say to him, 'Father, I have sinned against heaven and before you. I am no longer worthy to be called your son. Treat me as one of your hired servants.'\" And he arose and came to his father.\n\nBut while he was still a long way off, his father saw him and felt compassion, and ran and embraced him and kissed him. And the son said to him, \"Father, I have sinned against heaven and before you. I am no longer worthy to be called your son.\" But the father said to his servants, \"Bring quickly the best robe, and put it on him, and put a ring on his hand, and shoes on his feet. And bring the fattened calf and kill it, and let us eat and celebrate. For this my son was dead, and is alive again; he was lost, and is found.\" And they began to celebrate.",
        ref:"Luke 15:11-24", translation:"ESV", gospel:"luke",
        context:"Jesus told this parable \u2014 the third in a trilogy of lost-and-found stories \u2014 in direct response to the Pharisees' grumbling that He received sinners and ate with them. The parable is not primarily a story about repentance. It is primarily a story about a father. The father's response to the returning son is the theological center.",
        meaning:"Asking for the inheritance early was, in the cultural context of Jesus's day, an act equivalent to wishing the father dead. The father gives it anyway \u2014 a stunning portrayal of a God who allows His children to choose against Him.\n\nThe son's return is framed as \"coming to himself\" \u2014 a moment of clear-eyed recognition of his actual condition. His prepared speech is practical, not melodramatic: I have sinned, I am no longer worthy to be called your son, treat me as a servant.\n\nBut the father runs. Patriarchs did not run \u2014 running was undignified in that culture. The father has been watching, and the moment he sees his son \"while he was still a long way off,\" he abandons dignity entirely and runs toward him. The robe, ring, and shoes are not sentimental gestures \u2014 they are the reinstatement of full sonship. The fatted calf is not a reward for repentance. It is the explosion of a father's joy.",
        lexicon:[{word:"compassion",original:"σπλαγχνίζομαι (splanchnizomai)",language:"Greek",meaning:"To be deeply moved in the bowels; gut-level compassion.",note:"From AS1 W40. When the father in the parable sees his son returning, Luke says he was splanchnizomai — moved in the inner organs. The father did not wait for explanation, apology, or theological adjustment. The compassion was gut-deep and immediate. This is the Father Jesus reveals."},{word:"was dead",original:"νεκρός (nekros)",language:"Greek",meaning:"Dead; physically deceased; or, metaphorically, separated from life.",note:"The father says \"this son of mine was nekros and is alive again.\" Jesus is using death-and-resurrection language for what happens in repentance. The prodigal was not a struggling Christian. He was nekros. The return home was a resurrection."}],
        apply:"Do you believe the Father runs toward you? Not that He waits for you to fully arrive, not that He accepts you when you have cleaned up sufficiently \u2014 but that while you are still a long way off, He sees you and runs? The distance between the pig sty and the father's house is where the running happens. Where are you in that distance right now?",
        prayer:"Father, I have come to myself. I know what I left, I know what I wasted, I know I am not worthy to be called Your son or daughter. But I am coming home. I believe \u2014 I choose to believe \u2014 that You see me while I am still far off. You are already running. Meet me in the distance. Put the robe on me. Not because I deserve it. Because that is who You are. Amen.",
      },
    ]
  },
  {
    id:4, icon:"\u271d\ufe0f", title:"The Cross", subtitle:"The center of everything.",
    passages:[
      {
        id:"4_1", title:"Lifted Up Like Moses' Serpent",
        text:"No one has ascended into heaven except he who descended from heaven, the Son of Man. And as Moses lifted up the serpent in the wilderness, so must the Son of Man be lifted up, that whoever believes in him may have eternal life.\n\nFor God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life. For God did not send his Son into the world to condemn the world, but in order that the world might be saved through him.\n\nWhoever believes in him is not condemned, but whoever does not believe is condemned already, because he has not believed in the name of the only Son of God. And this is the judgment: the light has come into the world, and people loved the darkness rather than the light because their works were evil. For everyone who does wicked things hates the light and does not come to the light, lest his works should be exposed. But whoever does what is true comes to the light, so that it may be clearly seen that his works have been carried out in God.",
        ref:"John 3:13-21", translation:"ESV", gospel:"john",
        context:"Nicodemus \u2014 a Pharisee, a ruler of the Jews, a man of genuine religious standing \u2014 has come to Jesus at night. The conversation has moved from new birth to the nature of belief. Jesus now makes one of the most sweeping theological statements in the Gospels, including what would become the most recognized verse in Scripture.",
        meaning:"Jesus refers to Numbers 21 \u2014 when Moses lifted up a bronze serpent on a pole and all who looked at it were healed from snakebites \u2014 and applies it to Himself. The lifting up will be the cross. The looking that heals is belief. The wound is sin. The remedy is the lifted-up Son of Man.\n\nJohn 3:16 is not a standalone verse \u2014 it is the explanation of the lifting up. God's love is the origin of the giving; the giving is the means of eternal life. \"Condemned already\" is not God's sentence \u2014 it is the pre-existing condition of those who have not come to the light.\n\nThe passage closes with a description of two responses to the light: those who flee it (because it exposes what they are doing) and those who come to it (because they want their lives to be transparent before God). The response to the light is the self-revelation of the heart.",
        lexicon:[{word:"lifted up",original:"ὑψόω (hupsoō)",language:"Greek",meaning:"To lift up, exalt, raise high.",note:"Jesus uses hupsoō with deliberate double meaning. \"Just as Moses lifted up the serpent\" — physically raised on a pole. \"So must the Son of Man be lifted up\" — physically raised on a cross, AND exalted to the right hand of God. The cross is both shame and exaltation in one act."},{word:"loved",original:"ἀγαπάω (agapaō)",language:"Greek",meaning:"To love with willed, committed love.",note:"\"For God so agapaō-ed the world.\" The most famous verse in the Bible uses agapaō, not phileō. The love is willed, not warm — covenantal, decisive love. The world did nothing to earn it. God's love originated entirely in His own character."}],
        apply:"Are you coming toward the light or away from it? The test is not what you say but what you do with exposure. When the light of Scripture, of conversation, of the Spirit's conviction falls on something in your life, do you move toward it or manage the angle so it doesn't land? Come to the light today. Bring one specific thing that has been in the dark.",
        prayer:"Father, You so loved the world that You gave Your Son. You gave Him to be lifted up so that I could look and live. I look now. I see what that lifting up cost. I believe \u2014 not just intellectually, but with the looking that heals. I come to the light. I bring what I have kept in the darkness. You did not send Your Son to condemn me but to save me. I receive that today. Amen.",
      },
      {
        id:"4_2", title:"Words from the Cross",
        text:"Father, forgive them, for they know not what they do.\n\nTruly, I say to you, today you will be with me in paradise.\n\nWoman, behold, your son! Behold, your mother!\n\nMy God, my God, why have you forsaken me?\n\nI thirst.\n\nIt is finished.\n\nFather, into your hands I commit my spirit.",
        ref:"Luke 23:34; Luke 23:43; John 19:26-27; Matthew 27:46; John 19:28; John 19:30; Luke 23:46", translation:"ESV", gospel:"luke",
        context:"These are the seven last words of Jesus from the cross, drawn from all four Gospels. They span the full duration of the crucifixion \u2014 from the moment of nailing to the moment of death \u2014 and represent the final recorded words of Jesus before His resurrection.",
        meaning:"The seven words reveal the inner life of Jesus in extremis. The first is intercession for His killers \u2014 not silent endurance but active prayer on behalf of those causing the pain. The second is salvation extended to the thief beside Him \u2014 the kingdom accessible even at the final moment, through simple trust.\n\nThe fourth cry \u2014 \"My God, my God, why have you forsaken me?\" \u2014 is not theological confusion. It is Psalm 22:1, and Jesus is praying the psalm that the first-century Jew would have known ends in vindication and praise. He is not abandoned but is entering the full weight of human separation from God.\n\n\"It is finished\" (tetelestai) is a single word in Greek \u2014 a commercial term stamped on paid bills: debt settled. The work of atonement is not interrupted or partial. It is completed.\n\n\"Into your hands I commit my spirit\" is Psalm 31:5 \u2014 a Jewish bedtime prayer. He dies with a prayer of trust on His lips.",
        lexicon:[{word:"My God",original:"Ἐλωΐ (Eloi)",language:"Aramaic",meaning:"My God — the Aramaic form of the Hebrew Eli.",note:"On the cross, Jesus quoted Psalm 22:1 in Aramaic: \"Eloi, Eloi, lama sabachthani\" — \"My God, my God, why have You forsaken Me?\" The bystanders, hearing Aramaic, thought He was calling for Elijah. The cry was a real cry — and a real prayer, anchored in Scripture."},{word:"It is finished",original:"τετέλεσται (tetelestai)",language:"Greek",meaning:"It is finished, completed, fully paid.",note:"Tetelestai is the perfect tense — completed action with ongoing result. The word appears on ancient receipts marking debts paid in full. When Jesus said it on the cross, He was declaring the debt of sin paid completely. The work was done. Nothing remained to be added."}],
        apply:"Which of these words speaks most directly to where you are today? The prayer of forgiveness for those who have harmed you? The assurance that it is never too late to turn to Him? The cry of abandonment that He somehow carried so you would not be alone in yours? The declaration that the debt is settled? Receive the word that meets your condition.",
        prayer:"Jesus, You prayed for Your killers while they were still killing You. You promised paradise to a dying thief. You cried out from desolation and still committed Your spirit to the Father. It is finished \u2014 the debt I carried is paid. Into Your hands I commit my spirit today. Every word You spoke from the cross was for someone like me. I receive them all. Amen.",
      },
    ]
  },
  {
    id:5, icon:"\ud83c\udf31", title:"Discipleship", subtitle:"What it actually costs to follow.",
    passages:[
      {
        id:"5_1", title:"Take Up Your Cross",
        text:"If anyone would come after me, let him deny himself and take up his cross daily and follow me. For whoever would save his life will lose it, but whoever loses his life for my sake will save it. For what does it profit a man if he gains the whole world and loses or forfeits himself?\n\nFor whoever is ashamed of me and of my words, of him will the Son of Man be ashamed when he comes in his glory and the glory of the Father and of the holy angels. But I tell you truly, there are some standing here who will not taste death until they see the kingdom of God.",
        ref:"Luke 9:23-27", translation:"ESV", gospel:"luke",
        context:"Jesus had just told His disciples that He would suffer, be rejected, be killed, and rise on the third day. Peter rebuked Him. Jesus rebuked Peter. Then \u2014 addressing the crowd along with His disciples \u2014 He made discipleship explicit. This is not a private instruction to the Twelve but a public announcement to anyone who would follow.",
        meaning:"Three movements: deny yourself (dethrone the self from the center of decision-making), take up your cross daily (accept the specific cost of following Jesus in your particular life), and follow me (a direction, not a destination \u2014 it is relational and ongoing).\n\nLuke adds the word \"daily\" that Matthew's parallel does not include. This is not a one-time crisis decision but a practice renewed each morning. The cross is not generic suffering \u2014 every person's cross is custom-shaped to the specific cost their obedience requires.\n\nThe paradox Jesus describes is real: the person who holds tightly to their life loses it; the person who releases their life for Jesus saves it. The loss Jesus describes is not physical death but the forfeiture of the self \u2014 the person who gains everything the world offers but loses who they actually were created to be.",
        lexicon:[{word:"deny",original:"ἀπαρνέομαι (aparneomai)",language:"Greek",meaning:"To deny utterly; to disown, to refuse to claim.",note:"The same verb Peter used to deny Christ (Mark 14:30). Jesus turns it back: \"let him aparneomai himself.\" Self-denial is not deprivation — it is dethronement. The self is denied its claim to be the center, and Christ takes that place."},{word:"life",original:"ψυχή (psychē)",language:"Greek",meaning:"Soul, life, the whole inner person.",note:"\"Whoever would save his psychē will lose it.\" Psychē in Greek covers both physical life and inner life — what you are as a living person. Jesus warns: clutching it loses it. Losing it for His sake saves it. The kingdom economy reverses the world's math."}],
        apply:"What is your cross today \u2014 not suffering in general, but the specific thing Jesus is asking you to die to right now? Not a metaphor. A named, real, specific cost. Name it. Then pick it up. Discipleship is not a decision made once \u2014 it is a direction chosen every morning before the day's particular demands make choosing feel impossible.",
        prayer:"Jesus, I want to follow You. But I want to follow on my terms, carrying my preferences, going my direction. That is not following. Show me today's cross \u2014 the specific, named, daily thing. Give me grace to pick it up not with gritted teeth but with the trust that losing my life for You is the only way to actually find it. I deny myself. I pick it up. I follow. Amen.",
      },
      {
        id:"5_2", title:"Count the Cost",
        text:"If anyone comes to me and does not hate his own father and mother and wife and children and brothers and sisters, yes, and even his own life, he cannot be my disciple. Whoever does not bear his own cross and come after me cannot be my disciple.\n\nFor which of you, desiring to build a tower, does not first sit down and count the cost, whether he has enough to complete it? Otherwise, when he has laid a foundation and is not able to finish, all who see it begin to mock him, saying, \"This man began to build and was not able to finish.\"\n\nOr what king, going out to encounter another king in war, will not sit down first and deliberate whether he is able with ten thousand to meet him who comes against him with twenty thousand? And if not, while the other is yet a great way off, he sends a delegation and asks for terms of peace.\n\nSo therefore, any one of you who does not renounce all that he has cannot be my disciple.",
        ref:"Luke 14:26-33", translation:"ESV", gospel:"luke",
        context:"Large crowds were traveling with Jesus, and He turned and addressed them directly. Rather than encouraging the momentum, He issued a clarifying warning: following Him has a specific cost, and He wants people to count it before they commit rather than begin and abandon the project.",
        meaning:"The word \"hate\" in verse 26 is idiomatic Hebrew hyperbole \u2014 in comparison, not in absolute terms. Jesus is not commanding family hatred but family subordination. When following Jesus conflicts with family loyalty, Jesus wins. The love for Him must be so primary that every other love, by comparison, looks like hatred.\n\nThe two parables \u2014 the tower builder and the king at war \u2014 both make the same point: wisdom requires honest assessment of what you are getting into before you begin. Discipleship that hasn't counted the cost will fail when the cost arrives.\n\n\"Renounce all that he has\" does not necessarily mean material divestiture for every disciple. It means holding all possessions, relationships, and plans with an open hand \u2014 nothing owned, everything held in trust.",
        lexicon:[{word:"hate",original:"μισέω (miseō)",language:"Greek",meaning:"To hate; in Semitic idiom, to love less by comparison.",note:"Jesus's command to \"hate\" father and mother is Hebrew idiom — comparative, not absolute. The point is hierarchy: love for Him must so exceed all other loves that other loves look like \"hate\" by comparison. Jesus is not commanding actual hatred; He is commanding undivided primary allegiance."},{word:"renounce",original:"ἀποτάσσομαι (apotassomai)",language:"Greek",meaning:"To say goodbye to, to renounce, to take leave of.",note:"\"Whoever does not apotassomai all that he has cannot be My disciple.\" The verb means to deliberately say farewell — to formally release claim. Discipleship is open-handed, not white-knuckled. What is renounced may still be used, but it is no longer owned."}],
        apply:"Have you counted the cost? Not to discourage yourself, but to be honest about what you are signing up for. What specifically would following Jesus cost you \u2014 in your relationships, your career, your social standing, your comfort? Name it. Counted costs do not surprise you when they arrive. Uncounted costs become reasons to quit.",
        prayer:"Jesus, I want to follow You with clear eyes, not romantic illusions. I count the cost now: it costs me my right to be my own master, my right to prioritize family above Your call, my right to hold anything as ultimately mine. I renounce these rights not in despair but in trust that what You offer is worth more than what I release. I enter this with eyes open. Amen.",
      },
      {
        id:"5_3", title:"The Vine and the Branches",
        text:"I am the true vine, and my Father is the vinedresser. Every branch in me that does not bear fruit he takes away, and every branch that does bear fruit he prunes, that it may bear more fruit. Already you are clean because of the word that I have spoken to you.\n\nAbide in me, and I in you. As the branch cannot bear fruit by itself, unless it abides in the vine, neither can you, unless you abide in me. I am the vine; you are the branches. Whoever abides in me and I in him, he it is that bears much fruit, for apart from me you can do nothing.\n\nIf anyone does not abide in me he is thrown away like a branch and withers; and the branches are gathered, thrown into the fire, and burned. If you abide in me, and my words abide in you, ask whatever you wish, and it will be done for you. By this my Father is glorified, that you bear much fruit and so prove to be my disciples.",
        ref:"John 15:1-8", translation:"ESV", gospel:"john",
        context:"The night before the crucifixion, in the upper room after the Lord's Supper. Jesus is giving His farewell discourse \u2014 the most extended recorded teaching of His earthly ministry. The vine metaphor was deeply resonant: Israel was frequently described as God's vine in the Old Testament (Psalm 80, Isaiah 5). Jesus announces Himself as the true vine \u2014 the Israel that does not fail.",
        meaning:"The metaphor is precise and practical. A branch does not produce fruit through effort \u2014 it produces fruit by maintaining connection to the vine. The branch's entire output flows from its attachment. Jesus is not giving an aspirational call to try harder. He is describing the nature of spiritual life: it flows from connection, not from performance.\n\n\"Apart from me you can do nothing\" \u2014 the word \"nothing\" is absolute. Not less, not with difficulty, but nothing. The branches that bear fruit are pruned (cut) to produce more. The cutting is not punishment \u2014 it is the vinedresser's care for greater fruitfulness.\n\n\"My words abide in you\" in verse 7 is the means of abiding \u2014 being saturated in what Jesus has said, thinking with His words, being shaped by His teaching.",
        lexicon:[{word:"abide",original:"μένω (menō)",language:"Greek",meaning:"To remain, to stay connected.",note:"From AS1 W50. Jesus uses menō more than ten times in John 15. \"Abide in Me, and I in you.\" The branch's job is not productivity but connection. Fruit follows abiding; striving alone produces nothing. Many believers have reversed the order."},{word:"fruit",original:"καρπός (karpos)",language:"Greek",meaning:"Fruit; what is produced by an organism living according to its design.",note:"Karpos is the outcome, not the goal. A grapevine does not strive to produce grapes — it stays alive and bears them automatically. Christian karpos works the same way. Connection to the vine produces fruit. Detached effort produces nothing the vine produces."}],
        apply:"What are you currently trying to produce for God that you have not actually connected to Him through prayer, through His words, through honest dependence? The busy branch produces nothing. The connected branch produces inevitably. Before you do anything for God today, spend time in the vine \u2014 not as a prerequisite to earn His help, but as the actual source of what you will then carry into the day.",
        prayer:"Jesus, I am the branch. Apart from You I can do nothing \u2014 and I have been attempting quite a bit apart from You. Forgive the self-sufficient productivity that looks spiritual but is disconnected. I abide in You now. Let Your words abide in me \u2014 not as principles I have memorized but as living realities that shape how I see and respond. Bear fruit through me. I am the branch. You are the vine. Amen.",
      },
    ]
  },
  {
    id:6, icon:"\ud83d\udd4a\ufe0f", title:"Peace & Rest", subtitle:"The gift the world cannot give.",
    passages:[
      {
        id:"6_1", title:"Come to Me",
        text:"I thank you, Father, Lord of heaven and earth, that you have hidden these things from the wise and understanding and revealed them to little children; yes, Father, for such was your gracious will. All things have been handed over to me by my Father, and no one knows the Son except the Father, and no one knows the Father except the Son and anyone to whom the Son chooses to reveal him.\n\nCome to me, all who labor and are heavy laden, and I will give you rest. Take my yoke upon you, and learn from me, for I am gentle and lowly in heart, and you will find rest for your souls. For my yoke is easy, and my burden is light.",
        ref:"Matthew 11:25-30", translation:"ESV", gospel:"matthew",
        context:"Jesus has just completed a sustained section of teaching and condemnation of cities that had witnessed miracles and not repented. The religious leaders had been questioning His authority. In this context \u2014 at the low point of visible receptivity \u2014 Jesus breaks into praise. He thanks the Father for hiding these things from the sophisticated and revealing them to children.",
        meaning:"The invitation \"come to me\" is universal \u2014 \"all who labor and are heavy laden.\" The labor is not primarily physical but spiritual: the exhaustion of trying to perform your way to God, of carrying the weight of a religious system that demands everything and assures nothing.\n\nJesus offers an alternative to that system \u2014 not an absence of labor, but a different yoke. A yoke is a farming implement that joins two oxen to plow together. Jesus is not saying the Christian life is without effort. He is saying He is in the yoke with you, and His strength carries what your strength cannot.\n\n\"I am gentle and lowly in heart\" \u2014 this is the only place in the Gospels where Jesus describes His own character. And what He names is not power or authority but gentleness and humility. This is who you come to when you are exhausted.",
        lexicon:[{word:"weary",original:"κοπιάω (kopiaō)",language:"Greek",meaning:"To labor to exhaustion; to be worn out by hard work.",note:"Jesus addresses those who are kopiōntes — laboring to exhaustion. Not casual tiredness, but the deep weariness of carrying what cannot be carried. The invitation is precise: He calls the ones already worn out, not the ones who think they have it together."},{word:"yoke",original:"ζυγός (zugos)",language:"Greek",meaning:"A yoke; the wooden frame placed across the necks of working animals.",note:"Jesus offers a yoke — He does not offer no yoke. The choice is which yoke. The rabbi's \"yoke\" in Jesus's day meant his interpretation of Torah. Jesus says His yoke is chrēstos (kindly fit, well-formed). It is custom-shaped to the wearer. The rest is found in the right yoke, not in yokelessness."}],
        apply:"What are you laboring under that Jesus never asked you to carry? Not just workload \u2014 what spiritual weight have you picked up in religion, in performance, in the constant self-assessment of whether you are doing enough? Bring it specifically to Jesus today \u2014 not to a system, not to a discipline, to Him. Set it down in His presence. Let Him take it.",
        prayer:"Jesus, I labor. I am heavy laden. I am tired of the yoke I have been wearing \u2014 the one I picked up in religion, in self-improvement, in the endless project of becoming acceptable. I come to You. I take Your yoke \u2014 the one where You are in it with me, where Your strength carries what mine cannot. You are gentle. You are humble. You will not crush me. Give me rest for my soul. Amen.",
      },
      {
        id:"6_2", title:"Peace I Leave With You",
        text:"If you love me, you will keep my commandments. And I will ask the Father, and he will give you another Helper, to be with you forever, even the Spirit of truth, whom the world cannot receive, because it neither sees him nor knows him. You know him, for he dwells with you and will be in you. I will not leave you as orphans; I will come to you.\n\nPeace I leave with you; my peace I give to you. Not as the world gives do I give to you. Let not your hearts be troubled, neither let them be afraid. You heard me say to you, \"I am going away, and I will come to you.\" If you loved me, you would have rejoiced, because I am going to the Father, for the Father is greater than I. And now I have told you before it takes place, so that when it does take place you may believe.",
        ref:"John 14:15-18, 27-29", translation:"ESV", gospel:"john",
        context:"Upper room, night before the crucifixion. Thomas has just asked where Jesus is going and how to get there. Philip has asked to be shown the Father. The disciples are confused and frightened. Jesus speaks peace into an upper room full of grief and anxiety \u2014 hours before He will demonstrate it from the cross.",
        meaning:"The peace Jesus gives is qualitatively different from what the world offers. The world's peace is circumstantial \u2014 it exists when threats are absent, when situations are resolved, when the future is manageable. Jesus's peace exists independently of circumstances, because it flows from the nature of the Giver, not from the condition of the situation.\n\n\"Let not your hearts be troubled\" \u2014 this is a command, not a suggestion. It is addressed to the will, not to the emotions. You cannot command yourself to feel peaceful. But you can choose not to allow trouble to be the ruling principle of your heart, receiving by faith the peace that has been given.\n\n\"I will not leave you as orphans\" \u2014 the disciples felt the impending departure as abandonment. Jesus corrects this: departure is not abandonment. The Spirit who comes is not a consolation prize; He is the continuation of the same presence in a new mode.",
        lexicon:[{word:"peace",original:"εἰρήνη (eirēnē)",language:"Greek",meaning:"Peace; wholeness; the New Testament word that carries the weight of Hebrew shalom.",note:"From AS1 W17. \"Peace I leave with you; My peace I give to you.\" The peace Jesus gives is not the world's peace (which depends on circumstances). It is His own peace — the peace He carried into Gethsemane, the peace that operated underneath crucifixion. That peace, He says, becomes yours."},{word:"Helper",original:"παράκλητος (paraklētos)",language:"Greek",meaning:"One called alongside; advocate, comforter, counselor.",note:"From para (alongside) + kaleō (to call). The Holy Spirit is the paraklētos — the one called alongside to help. The verb form (parakaleō) is used of Christian encouragement (AS1 W29). The Spirit does in the believer what believers do for each other — comes alongside in time of need."}],
        apply:"Where is your heart troubled right now? Name the specific anxiety \u2014 the thing that wakes you at 3am, the relationship that has no clear resolution, the future that feels unstable. Do not pretend it is not there. And do not let it be the ruling center of your heart. Receive the peace that has already been given \u2014 not manufactured by you, but received from Him.",
        prayer:"Jesus, Your peace is not the absence of trouble. The disciples' situation was genuinely threatening. Mine is too. But You say: let not your hearts be troubled. I receive that as a command I can actually obey with Your help. I receive Your peace \u2014 not as a feeling I generate, but as a gift You have given. It does not depend on my circumstances being resolved. It depends on Your character being consistent. Let that be enough for today. Amen.",
      },
    ]
  },
  {
    id:7, icon:"\ud83c\udf3f", title:"Anxiety & Worry", subtitle:"What to do with tomorrow.",
    passages:[
      {
        id:"7_1", title:"Do Not Be Anxious",
        text:"Therefore I tell you, do not be anxious about your life, what you will eat or what you will drink, nor about your body, what you will put on. Is not life more than food, and the body more than clothing? Look at the birds of the air: they neither sow nor reap nor gather into barns, and yet your heavenly Father feeds them. Are you not of more value than they? And which of you by being anxious can add a single hour to his span of life?\n\nAnd why are you anxious about clothing? Consider the lilies of the field, how they grow: they neither toil nor spin, yet I tell you, even Solomon in all his glory was not arrayed like one of these. But if God so clothes the grass of the field, which today is alive and tomorrow is thrown into the oven, will he not much more clothe you, O you of little faith?\n\nTherefore do not be anxious, saying, \"What shall we eat?\" or \"What shall we drink?\" or \"What shall we wear?\" For the Gentiles seek after all these things, and your heavenly Father knows that you need them all. But seek first the kingdom of God and his righteousness, and all these things will be added to you.\n\nTherefore do not be anxious about tomorrow, for tomorrow will be anxious for itself. Sufficient for the day is its own trouble.",
        ref:"Matthew 6:25-34", translation:"ESV", gospel:"matthew",
        context:"This passage is the second major section of the central discourse of the Sermon on the Mount. Jesus has just addressed treasures and masters (you cannot serve God and money). He now addresses the anxiety that results from trying to serve the wrong master. Anxiety is the emotional consequence of misplaced ultimate allegiance.",
        meaning:"Jesus does not say worry is irrational. He says it is disproportionate \u2014 treating your life as though its central problem is food, clothing, and physical survival, when your life was given to you for something far larger.\n\nHe points to observable creation: birds that do not farm and yet are fed; lilies that do not labor and yet are clothed more beautifully than Solomon. The argument is from lesser to greater: if God attends to creatures that cannot acknowledge Him, how much more will He attend to you?\n\n\"Seek first the kingdom of God\" is the positive reorientation. Anxiety is the result of seeking the wrong things first. The antidote is not trying harder to stop worrying \u2014 it is redirecting the seeking toward God's kingdom, which then changes the weight of everything else.",
        apply:"What specific tomorrow are you living in today? What future scenario is consuming your present attention? Name it specifically. Then ask: what does it look like to seek God's kingdom in this present moment, in this actual day, rather than managing an imagined future? You cannot control tomorrow. You can choose what you seek today.",
        prayer:"Father, I have been living in tomorrow. I have been spending today's resources \u2014 attention, emotional energy, peace \u2014 managing a future that belongs to You. I return to today. I bring my anxiety about [name it specifically] and I receive Your word: Your Father knows. I seek first Your kingdom. The rest \u2014 You said so \u2014 will be added. I trust that. Not with performed confidence, but with a genuine choice to believe You. Amen.",
      },
    ]
  },
  {
    id:8, icon:"\ud83d\udca1", title:"Truth & Freedom", subtitle:"The truth that sets you free.",
    passages:[
      {
        id:"8_1", title:"The Way, the Truth, and the Life",
        text:"Let not your hearts be troubled. Believe in God; believe also in me. In my Father's house are many rooms. If it were not so, would I have told you that I go to prepare a place for you? And if I go and prepare a place for you, I will come again and will take you to myself, that where I am you may be also. And you know the way to where I am going.\n\nThomas said to him, \"Lord, we do not know where you are going. How can we know the way?\" Jesus said to him, \"I am the way, and the truth, and the life. No one comes to the Father except through me. If you had known me, you would have known my Father also. From now on you do know him and have seen him.\"",
        ref:"John 14:1-7", translation:"ESV", gospel:"john",
        context:"The night before the crucifixion, upper room. Jesus has just told His disciples He is going somewhere they cannot follow. The room is full of anxiety. Thomas \u2014 the one who always needs to see clearly \u2014 asks the question honestly: we don't know where You're going, so how can we know the way?",
        meaning:"Jesus's answer is not a direction \u2014 it is a person. The way to the Father is not a religious system, a moral achievement, a level of spiritual performance, or a philosophical conclusion. It is relationship with Jesus Himself.\n\nThree nouns, each claiming totality: the way (not a way), the truth (not a truth), the life (not a life). This is the most exclusive claim in the Gospels \u2014 and it is not made as a theological proposition but as pastoral comfort to frightened disciples.\n\n\"No one comes to the Father except through me\" \u2014 the exclusivity is not triumphalism. It is the nature of the gift. Relationship with the Father is not a self-service option. It flows through relationship with the Son.",
        apply:"In what areas of your life are you trying to reach God through something other than Jesus \u2014 through your goodness, your religious performance, your spiritual disciplines as merit? He said: I am the way. Not an addition to your spiritual path. The path itself. Come through Him, not around Him. Stop managing your approach and simply come.",
        prayer:"Jesus, You are the way \u2014 I do not have to find my own path, I just have to follow You. You are the truth \u2014 I do not have to construct my own meaning, I just have to receive what is real. You are the life \u2014 I do not have to generate it myself, I just have to stay connected to You. In my fear about the future, in my uncertainty about where this is all going, You say: believe in God, believe also in me. I do. Amen.",
      },
      {
        id:"8_2", title:"The Truth Will Set You Free",
        text:"So Jesus said to the Jews who had believed him, \"If you abide in my word, you are truly my disciples, and you will know the truth, and the truth will set you free.\"\n\nThey answered him, \"We are offspring of Abraham and have never been enslaved to anyone. How is it that you say, 'You will become free'?\"\n\nJesus answered them, \"Truly, truly, I say to you, everyone who practices sin is a slave to sin. The slave does not remain in the house forever; the son remains forever. So if the Son sets you free, you will be free indeed.\"",
        ref:"John 8:31-36", translation:"ESV", gospel:"john",
        context:"Jesus is teaching in the temple courts during the Feast of Tabernacles. He has just declared \"I am the light of the world.\" Now He is speaking to Jews who had believed in Him \u2014 not skeptics but initial believers \u2014 and pressing them beyond initial faith toward genuine discipleship. He is distinguishing between belief as intellectual assent and belief as committed abiding.",
        meaning:"The condition for knowing the truth is abiding in the word \u2014 remaining in it, living inside it, being shaped by it over time. This is not an endorsement of biblical literacy as an end in itself but of the transformation that comes when Scripture is not just known but inhabited.\n\nThe freedom Jesus promises is not political or philosophical. It is liberation from the compulsive patterns of sin \u2014 the patterns that a person cannot break by willpower alone, that feel like walls from the inside. The slave cannot free himself. Only the Son can set you free. And the freedom the Son gives is not conditional on sustained performance \u2014 it is \"free indeed.\"",
        apply:"What lie are you living inside right now \u2014 about your worth, about God's nature, about what you deserve, about what will satisfy you? The lie is the chain. The corresponding truth in Jesus's words is the key. Identify the lie specifically. Then find what Jesus says that directly contradicts it. Not a general truth \u2014 the specific truth that addresses the specific lie. Apply it by speaking it, writing it, praying it daily until it displaces the lie.",
        prayer:"Jesus, I want the truth that sets free \u2014 not as information I can articulate but as liberation I actually experience. Show me the specific lie I have been living in. I am willing to abide in Your word even when it contradicts my preferred story about myself. Set me free. Not from difficulty \u2014 from the chains I cannot break alone. If the Son sets me free, I am free indeed. I claim that today. Amen.",
      },
    ]
  },
  {
    id:9, icon:"\u26a1", title:"The Holy Spirit", subtitle:"The promise of His presence.",
    passages:[
      {
        id:"9_1", title:"The Spirit of Truth",
        text:"If you love me, you will keep my commandments. And I will ask the Father, and he will give you another Helper, to be with you forever, even the Spirit of truth, whom the world cannot receive, because it neither sees him nor knows him. You know him, for he dwells with you and will be in you.\n\nBut the Helper, the Holy Spirit, whom the Father will send in my name, he will teach you all things and bring to your remembrance all that I have said to you.\n\nWhen the Spirit of truth comes, he will guide you into all the truth, for he will not speak on his own authority, but whatever he hears he will speak, and he will declare to you the things that are to come. He will glorify me, for he will take what is mine and declare it to you. All that the Father has is mine; therefore I said that he will take what is mine and declare it to you.",
        ref:"John 14:15-17, 26; 16:13-15", translation:"ESV", gospel:"john",
        context:"The upper room discourse. Jesus is preparing His disciples for His physical departure by introducing them to who is coming \u2014 not as a substitute for His presence but as the continuation of it in a new mode. The disciples are experiencing this as loss. Jesus is framing it as gain.",
        meaning:"The Spirit is described with three primary functions: Helper (one called alongside to assist), Teacher (who brings Jesus's words to remembrance), and Guide into truth (who connects the disciples to what is yet to come).\n\nThe Spirit does not speak independently \u2014 He speaks what He hears from the Son and the Father. His ministry is fundamentally Christocentric: He takes what belongs to Jesus and makes it known to the disciples. This means that genuine experiences of the Spirit will always produce greater clarity about Jesus, not lesser.\n\n\"He will glorify me\" \u2014 any spiritual experience that shifts attention away from Jesus is not the Spirit's work. The Spirit consistently points toward the Son.",
        apply:"When is the last time you paused in a moment of confusion, fear, or decision and genuinely asked the Holy Spirit to teach you, to bring Jesus's words to remembrance, to guide you into the truth about your situation? He was sent for exactly this. Practice it today: in the next difficulty you face, before you react or strategize, ask the Spirit what Jesus would say about this.",
        prayer:"Holy Spirit, You were sent to teach me everything and remind me of all that Jesus said. I have not been asking. I have been going to other sources first \u2014 my own analysis, other people's opinions, past patterns. I ask now: teach me. Bring to my remembrance what Jesus has said that applies to what I am facing today. Guide me into the truth I need right now. Glorify Jesus in how I live today. Amen.",
      },
    ]
  },
  {
    id:10, icon:"\ud83c\udf05", title:"Resurrection & Life", subtitle:"The life that death cannot interrupt.",
    passages:[
      {
        id:"10_1", title:"I Am the Resurrection and the Life",
        text:"When Jesus therefore saw her weeping, and the Jews also weeping which came with her, he groaned in the spirit, and was troubled. And said, Where have ye laid him? They said unto him, Lord, come and see. Jesus wept.\n\nMartha said to him, \"Lord, if you had been here, my brother would not have died. But even now I know that whatever you ask from God, God will give you.\"\n\nJesus said to her, \"Your brother will rise again.\" Martha said to him, \"I know that he will rise again in the resurrection on the last day.\" Jesus said to her, \"I am the resurrection and the life. Whoever believes in me, though he die, yet shall he live, and everyone who lives and believes in me shall never die. Do you believe this?\"",
        ref:"John 11:21-22, 23-26 (with v.33-35)", translation:"ESV", gospel:"john",
        context:"Lazarus has been dead four days. His sisters Martha and Mary have sent for Jesus, who delayed. When He finally arrives, Martha comes to meet Him. Her words carry both faith and accusation: \"If you had been here.\" Jesus responds not with explanation but with a question that is really a declaration.",
        meaning:"Martha's faith in the resurrection is orthodox and correct \u2014 \"I know that he will rise again in the resurrection on the last day.\" Jesus does not correct her theology. He relocates it: the resurrection is not a future event to be hoped for; it is a present person to be encountered. \"I AM the resurrection\" \u2014 not I will cause it, not I will initiate it, but I AM it.\n\nJesus wept. The shortest verse in the Bible carries enormous weight. He is the resurrection and the life \u2014 He is about to raise Lazarus. And He still weeps. He does not weep because He doesn't know the outcome. He weeps because the loss is real, the grief is real, the suffering is real, and He enters it fully.\n\nThis is the character of the one who claims to be the resurrection: He does not manage suffering from a distance. He groans in spirit and weeps.",
        apply:"What in your life feels like a four-day-dead situation \u2014 beyond hope, past the point where you believed God might show up? Bring it to the One who is the resurrection, not the One who causes it from a distance. He is the resurrection. Wherever He is present, that principle is in the room. Is there anything too dead for the One who is the life itself?",
        prayer:"Jesus, You are the resurrection and the life. I bring You the thing that feels four days dead \u2014 the dream, the relationship, the hope I have stopped hoping for. You wept. You felt the weight of what death does, and You wept. And then You called him out. Enter my grief. Weep with what I have lost. And then speak \u2014 because where You are, death does not get the final word. I believe this. Help my unbelief. Amen.",
      },
      {
        id:"10_2", title:"The Bread of Life",
        text:"Truly, truly, I say to you, whoever believes has eternal life. I am the bread of life. Your fathers ate the manna in the wilderness, and they died. This is the bread that comes down from heaven, so that one may eat of it and not die. I am the living bread that came down from heaven. If anyone eats of this bread, he will live forever. And the bread that I will give for the life of the world is my flesh.\n\nSo Jesus said to them, \"Truly, truly, I say to you, unless you eat the flesh of the Son of Man and drink his blood, you have no life in you. Whoever feeds on my flesh and drinks my blood has eternal life, and I will raise him up on the last day. For my flesh is true food, and my blood is true drink. Whoever feeds on my flesh and drinks my blood abides in me, and I in him. As the living Father sent me, and I live because of the Father, so whoever feeds on me, he also will live because of me. This is the bread that came down from heaven, not like the bread the fathers ate, and died. Whoever feeds on this bread will live forever.\"",
        ref:"John 6:47-58", translation:"ESV", gospel:"john",
        context:"The day after feeding the five thousand, Jesus has been teaching in the synagogue at Capernaum. The crowd has followed Him across the lake looking for more bread. He redirects them from the physical bread they want to the true bread He is. Many of His disciples will leave after this teaching \u2014 He refuses to soften it.",
        meaning:"Jesus is making a deliberately shocking claim using the language of eating and drinking His flesh and blood \u2014 language that would have sounded sacrilegious to Jewish ears. He is not instituting the Lord's Supper here (that comes later), but He is using visceral, physical metaphors to describe a spiritual reality: genuine participation in His life through faith.\n\nThe contrast with manna is precise: the fathers ate manna and still died. This bread \u2014 Jesus Himself \u2014 produces life that does not end. The bread of life is not a resource Jesus provides. It is Jesus Himself, received through believing trust that is as intimate and sustaining as eating.\n\n\"He will raise him up on the last day\" \u2014 the promise of resurrection is tied to present receiving of Jesus. The future is secured by the current relationship.",
        apply:"Are you receiving Jesus the way you receive food \u2014 regularly, out of genuine hunger, because you cannot live without it \u2014 or occasionally, when you remember to, when the schedule allows? The metaphor is intentional: you cannot stockpile last week's bread. You need today's. What does it look like to feed on Jesus today, in this day's specific hungers?",
        prayer:"Jesus, You are the bread that came down from heaven. I am hungry in ways that other bread has not satisfied. I feed on You today \u2014 not on a doctrine about You, not on memories of past experiences of You, but on You, present and living, the bread that produces life that does not end. I receive You. I abide in You. Raise me on the last day. Live in me today. Amen.",
      },
    ]
  },
]

export const ALL_PASSAGES = THEMES.flatMap(t => t.passages.map(p => ({ ...p, themeId: t.id, themeTitle: t.title, themeIcon: t.icon })))

export const GOSPEL_COLORS = { matthew:'#9B2020', mark:'#1A6B4A', luke:'#1A4B8B', john:'#6B2A8B' }
